spring:
  datasource:
    url: jdbc:mysql://localhost:3306/read_data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: springuser
    password: ThePassword
    driver-class-name: com.mysql.cj.jdbc.Driver
